### ISSUE TITLE
theme for hexo?

### ISSUE THREAD

**Issue by cokePanda** [nadjetey/wangana#8]
Hi, I like the theme. Do you plan to rewrite it for [hexo](http://hexo.io) which I am applying on right now?
And do you limit the number of posts listed on the home page?

thanks,
Jake

**Comment by nadjetey** [comment]
Thanks @cokePanda Rewriting it for hexo shouldn't be a problem (if you are interested we can port it together, should be fun)

The number of posts have not been limited, I was trying to implement unlimited scrolling. It's just as straight forward to limit it if that's what you want

Regards, 
Nii

**Comment by cokePanda** [comment]
I am just learning to modify some part of a theme to publish my blog, so it is kind of a challenge for me to transplant it from jekyll to hexo. But it is really interesting. Amateur coder I call myself.
I noticed that the archive page does not include posts from the home page  which is confusing to me.
And maybe on the home page adding a thumbnail around  post title is a good idea?

thanks,
Jake

**Comment by nadjetey** [comment]
From my understanding of hexo and jekyll, I would say the two are very similar. Where is your blog source code hosted? Link to your source code and I would be happy to help you port wangana and even modify to your taste. 

You are correct, the archive posts are not part of the list of posts on the home page, I coded it like that. I wanted a way to tuck away some posts and leave the more 'valuable' posts on the home page.

**Comment by cokePanda** [comment]
Hexo is more convenient to operate or say more friendly for me, and many bloggers mentioned that jekyll runs  intolerably slowly when compiling plenty of post files. So I believe that more people would like to apply your theme on hexo since it really looks compact and  elegant to publish their blogs.

Thanks for your kind. I already installed jekyll and tried to modify wangana theme locally. If any questions, I will ask for your help. Look forward to the hexo version of wangana.

thanks.

**Comment by nadjetey** [comment]
Awesome, thanks for your interest in wangana.

I dont think the bloggers you talked to are correct. From what I understand of the technology, Jekyll compiles all posts once (during deployment) into static html files which renders very fast &mdash; after its compiled, every time a request is made, the static files are served. Jekyll has been proven to be super fast in comparison to other blog-like technology. I don't understand how they can say it's slow, I'm tempted to think there is something more going on. Those bloggers are probably doing somethings wrong.

Anyways, if you have already decided to use hexo instead of jekyll I respect that. Good luck.

Regards, 
Nii

**Comment by cokePanda** [comment]
Anyway, you did a good work. Keep going.
